services:
  handoff:
    build: ./Backend
    tty: true           
    stdin_open: true    
    restart: always
    ports:
      - "14553:14553/udp"
      - "3003:3003"
    
  webserver:
    build: ./Frontend
    restart: always
    ports:
    - "5173:5173"
  mavproxy:
    image: sitin/mavproxy:latest
    stdin_open: true   
    tty: true          
    network_mode: "host"
    restart: always
    command:
        - --master
        - tcp:192.168.10.11:14553 #vehicle 1
        - --baud
        - "57600"
        - --out
        - host.docker.internal:14553
        - --out
        - host.docker.internal:14550
        - --streamrate=-1
        - --nowait
    ports:
      - "14553:14553"
      - "14550:14550"
  mapserver:
    image: maptiler/tileserver-gl:latest
    ports:
      - "8003:8080"
    volumes:
      - /Users/lukescholler/Documents/mapdata:/data
    command: ["--file", "daytonsat.mbtiles"]
    restart: unless-stopped
  nginx:
    image: nginx:alpine
    ports:
      - "8004:80"
    depends_on:
      - mapserver
    command: |
      /bin/sh -c "
      cat > /etc/nginx/nginx.conf << 'EOF'
      events { worker_connections 1024; }
      http {
        gzip on;
        gzip_types text/plain application/json image/png;
        proxy_cache_path /tmp/nginx_cache levels=1:2 keys_zone=tile_cache:10m max_size=1g inactive=60m use_temp_path=off;
        server {
          listen 80;
          location / {
            proxy_pass http://mapserver:8080;
            proxy_cache tile_cache;
            proxy_cache_valid 200 24h;
            proxy_cache_valid 404 1m;
            
            # Remove any existing CORS headers from upstream
            proxy_hide_header Access-Control-Allow-Origin;
            proxy_hide_header Access-Control-Allow-Methods;
            proxy_hide_header Access-Control-Allow-Headers;
            
            # Add our own CORS headers
            add_header Cache-Control 'public, max-age=86400';
            add_header Access-Control-Allow-Origin '*';
            add_header Access-Control-Allow-Methods 'GET, OPTIONS';
            add_header X-Cache-Status \$$upstream_cache_status;
          }
        }
      }
      EOF
      nginx -g 'daemon off;'
      "